controller_frequency: 5.0
recovery_behavior_enabled: true
planner_frequency: 0.0
planner_patience: 10.0
max_planning_retries: 1
clearing_rotation_allowed: true

GlobalPlanner:
  allow_unknown: false
  use_dijkstra: false
  use_voronoi: true
  use_astar_tuw: true
  heuristics_weight: 1.0
  visualize_potential: true
  cost_factor: 0.55
  neutral_cost: 66

NavfnROS:
  allow_unknown: true # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  default_tolerance: 0.1 # A tolerance on the goal point for the planner.

WaypointGlobalPlanner:
  epsilon: 1e-1  # distance threshold for final waypoint
  waypoints_per_meter: 20  # number of waypoints per meter for the interpolation of the path
  
nmpcPlannerROS:
  acc_lim_x: 0.15
  acc_lim_y: 0.1
  acc_lim_theta: 0.52
  speed_lim: 0.5
  steer_lim: 1.0
  xICR: 0.00248
  width: 0.5
  
  odom_topic: odom
  global_plan_prune_distance: 1.0
  xy_goal_tolerance: 1.0
  max_global_plan_lookahead_dist: 5.0 # Check horizon length
  seg_inflation_rate: 0.1
  use_voronoi: true
  obstacle_avoidance: true
  check_feasibility: true
  feasibility_window: 15
  min_path_width: 3.0

  weight_x:  20.0         # Weighting matrix for X-coordinate
  weight_y: 20.0    # Weighting matrix for Y-coordinate
  weight_theta: 0.0         # Weighting factor for heading
  weight_speed: 10.0   # Weighting matrix for velocity
  weight_final_x: 30.0     # Weighting matrix for X-coordinate at final point
  weight_final_y: 10.0    # Weighting matrix for Y-coordinate at final point
  weight_final_theta: 20.0
  weight_final_speed: 10.0
  weight_acc: 30.0
  weight_steer: 10.0   # Weighting matrix for steering angle
  weight_steer_acc: 10.0
  weight_left_side: 10.0
  weight_right_side: 10
  weight_obs: 10
  weight_y_obs: 0.1

  num_trajecotry_points: 20
  time_interval: 0.2

  use_c_code: true
  generate_c: false
  use_irk: false
  print_level: 0
  collocation_points: 3.0
  linear_solver: ma27
  nlp_solver_name: nmpc_solver_whizzy_devel


TrajectoryPlannerROS:
  # Robot Configuration Parameters
  acc_lim_x: 2.5
  acc_lim_theta:  3.2

  max_vel_x: 1.0
  min_vel_x: 0.0

  max_vel_theta: 0.2
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.2

  holonomic_robot: false
  escape_vel: -0.1

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 20.0
  sim_granularity: 0.02
  angular_sim_granularity: 0.02
  vx_samples: 10
  vtheta_samples: 20
  controller_frequency: 20.0

  # Trajectory scoring parameters
  meter_scoring: true # Whether the gdist_scale and pdist_scale parameters should assume that goal_distance and path_distance are expressed in units of meters or cells. Cells are assumed by default (false).
  occdist_scale:  0.1 #The weighting for how much the controller should attempt to avoid obstacles. default 0.01
  path_distance_bias: 0.01  #     The weighting for how much the controller should stay close to the path it was given . default 0.6
  goal_distance_bias: 1.0 #     The weighting for how much the controller should attempt to reach its local goal, also controls speed  default 0.8

  heading_lookahead: 0.325  #How far to look ahead in meters when scoring different in-place-rotation trajectories
  heading_scoring: false  #Whether to score based on the robot's heading to the path or its distance from the path. default false
  heading_scoring_timestep: 0.8   #How far to look ahead in time in seconds along the simulated trajectory when using heading scoring (double, default: 0.8)
  dwa: true #Whether to use the Dynamic Window Approach (DWA)_ or whether to use Trajectory Rollout
  simple_attractor: false
  publish_cost_grid_pc: true  
  max_rotational_vel: 0.2
  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.25 #How far the robot must travel in meters before oscillation flags are reset (double, default: 0.05)
  escape_reset_dist: 0.1
  escape_reset_theta: 0.1

DWAPlannerROS:
  # Robot configuration parameters  
  acc_lim_x: 2.5
  acc_lim_y: 0
  acc_lim_th: 3.2

  max_vel_x: 0.5
  min_vel_x: 0.0
  max_vel_y: 0
  min_vel_y: 0

  max_vel_trans: 0.5
  min_vel_trans: 0.1
  max_vel_theta: 1.0
  min_vel_theta: 0.2

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false