//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the nmpc_local_planner package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __nmpc_local_planner__NMPCLOCALPLANNERRECONFIGURECONFIG_H__
#define __nmpc_local_planner__NMPCLOCALPLANNERRECONFIGURECONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace nmpc_local_planner
{
  class NmpcLocalPlannerReconfigureConfigStatics;

  class NmpcLocalPlannerReconfigureConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(NmpcLocalPlannerReconfigureConfig &config, const NmpcLocalPlannerReconfigureConfig &max, const NmpcLocalPlannerReconfigureConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const NmpcLocalPlannerReconfigureConfig &config1, const NmpcLocalPlannerReconfigureConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, NmpcLocalPlannerReconfigureConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const NmpcLocalPlannerReconfigureConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, NmpcLocalPlannerReconfigureConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const NmpcLocalPlannerReconfigureConfig &config) const = 0;
      virtual void getValue(const NmpcLocalPlannerReconfigureConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T NmpcLocalPlannerReconfigureConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T NmpcLocalPlannerReconfigureConfig::* field;

      virtual void clamp(NmpcLocalPlannerReconfigureConfig &config, const NmpcLocalPlannerReconfigureConfig &max, const NmpcLocalPlannerReconfigureConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const NmpcLocalPlannerReconfigureConfig &config1, const NmpcLocalPlannerReconfigureConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, NmpcLocalPlannerReconfigureConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const NmpcLocalPlannerReconfigureConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, NmpcLocalPlannerReconfigureConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const NmpcLocalPlannerReconfigureConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const NmpcLocalPlannerReconfigureConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, NmpcLocalPlannerReconfigureConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, NmpcLocalPlannerReconfigureConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<NmpcLocalPlannerReconfigureConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(NmpcLocalPlannerReconfigureConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);


      }
    }

    

    bool state;
    std::string name;

    class CONTROLLER
{
  public:
    CONTROLLER()
    {
      state = true;
      name = "controller";
    }

    void setParams(NmpcLocalPlannerReconfigureConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("weight_x"==(*_i)->name){weight_x = boost::any_cast<double>(val);}
        if("weight_y"==(*_i)->name){weight_y = boost::any_cast<double>(val);}
        if("weight_theta"==(*_i)->name){weight_theta = boost::any_cast<double>(val);}
        if("weight_speed"==(*_i)->name){weight_speed = boost::any_cast<double>(val);}
        if("weight_final_x"==(*_i)->name){weight_final_x = boost::any_cast<double>(val);}
        if("weight_final_y"==(*_i)->name){weight_final_y = boost::any_cast<double>(val);}
        if("weight_final_theta"==(*_i)->name){weight_final_theta = boost::any_cast<double>(val);}
        if("weight_final_speed"==(*_i)->name){weight_final_speed = boost::any_cast<double>(val);}
        if("weight_acc"==(*_i)->name){weight_acc = boost::any_cast<double>(val);}
        if("weight_steer"==(*_i)->name){weight_steer = boost::any_cast<double>(val);}
        if("weight_steer_acc"==(*_i)->name){weight_steer_acc = boost::any_cast<double>(val);}
        if("weight_left_side"==(*_i)->name){weight_left_side = boost::any_cast<double>(val);}
        if("weight_right_side"==(*_i)->name){weight_right_side = boost::any_cast<double>(val);}
        if("weight_obs"==(*_i)->name){weight_obs = boost::any_cast<double>(val);}
      }
    }

    double weight_x;
double weight_y;
double weight_theta;
double weight_speed;
double weight_final_x;
double weight_final_y;
double weight_final_theta;
double weight_final_speed;
double weight_acc;
double weight_steer;
double weight_steer_acc;
double weight_left_side;
double weight_right_side;
double weight_obs;

    bool state;
    std::string name;

    
}controller;

}groups;



//#line 24 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      double weight_x;
//#line 25 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      double weight_y;
//#line 26 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      double weight_theta;
//#line 27 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      double weight_speed;
//#line 28 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      double weight_final_x;
//#line 29 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      double weight_final_y;
//#line 30 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      double weight_final_theta;
//#line 31 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      double weight_final_speed;
//#line 32 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      double weight_acc;
//#line 33 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      double weight_steer;
//#line 34 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      double weight_steer_acc;
//#line 35 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      double weight_left_side;
//#line 36 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      double weight_right_side;
//#line 37 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      double weight_obs;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("NmpcLocalPlannerReconfigureConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const NmpcLocalPlannerReconfigureConfig &__max__ = __getMax__();
      const NmpcLocalPlannerReconfigureConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const NmpcLocalPlannerReconfigureConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const NmpcLocalPlannerReconfigureConfig &__getDefault__();
    static const NmpcLocalPlannerReconfigureConfig &__getMax__();
    static const NmpcLocalPlannerReconfigureConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const NmpcLocalPlannerReconfigureConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void NmpcLocalPlannerReconfigureConfig::ParamDescription<std::string>::clamp(NmpcLocalPlannerReconfigureConfig &config, const NmpcLocalPlannerReconfigureConfig &max, const NmpcLocalPlannerReconfigureConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class NmpcLocalPlannerReconfigureConfigStatics
  {
    friend class NmpcLocalPlannerReconfigureConfig;

    NmpcLocalPlannerReconfigureConfigStatics()
    {
NmpcLocalPlannerReconfigureConfig::GroupDescription<NmpcLocalPlannerReconfigureConfig::DEFAULT, NmpcLocalPlannerReconfigureConfig> Default("Default", "", 0, 0, true, &NmpcLocalPlannerReconfigureConfig::groups);
NmpcLocalPlannerReconfigureConfig::GroupDescription<NmpcLocalPlannerReconfigureConfig::DEFAULT::CONTROLLER, NmpcLocalPlannerReconfigureConfig::DEFAULT> controller("controller", "tab", 0, 1, true, &NmpcLocalPlannerReconfigureConfig::DEFAULT::controller);
//#line 24 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __min__.weight_x = 0.0;
//#line 24 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __max__.weight_x = 1000.0;
//#line 24 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __default__.weight_x = 10.0;
//#line 24 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      controller.abstract_parameters.push_back(NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::ParamDescription<double>("weight_x", "double", 0, "Weight parameters for state x", "", &NmpcLocalPlannerReconfigureConfig::weight_x)));
//#line 24 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::ParamDescription<double>("weight_x", "double", 0, "Weight parameters for state x", "", &NmpcLocalPlannerReconfigureConfig::weight_x)));
//#line 25 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __min__.weight_y = 0.0;
//#line 25 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __max__.weight_y = 1000.0;
//#line 25 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __default__.weight_y = 10.0;
//#line 25 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      controller.abstract_parameters.push_back(NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::ParamDescription<double>("weight_y", "double", 0, "Weight parameters for  state x", "", &NmpcLocalPlannerReconfigureConfig::weight_y)));
//#line 25 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::ParamDescription<double>("weight_y", "double", 0, "Weight parameters for  state x", "", &NmpcLocalPlannerReconfigureConfig::weight_y)));
//#line 26 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __min__.weight_theta = 0.0;
//#line 26 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __max__.weight_theta = 1000.0;
//#line 26 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __default__.weight_theta = 10.0;
//#line 26 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      controller.abstract_parameters.push_back(NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::ParamDescription<double>("weight_theta", "double", 0, "Weight parameters for state theta", "", &NmpcLocalPlannerReconfigureConfig::weight_theta)));
//#line 26 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::ParamDescription<double>("weight_theta", "double", 0, "Weight parameters for state theta", "", &NmpcLocalPlannerReconfigureConfig::weight_theta)));
//#line 27 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __min__.weight_speed = 0.0;
//#line 27 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __max__.weight_speed = 1000.0;
//#line 27 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __default__.weight_speed = 10.0;
//#line 27 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      controller.abstract_parameters.push_back(NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::ParamDescription<double>("weight_speed", "double", 0, "Weight parameters for state speed", "", &NmpcLocalPlannerReconfigureConfig::weight_speed)));
//#line 27 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::ParamDescription<double>("weight_speed", "double", 0, "Weight parameters for state speed", "", &NmpcLocalPlannerReconfigureConfig::weight_speed)));
//#line 28 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __min__.weight_final_x = 0.0;
//#line 28 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __max__.weight_final_x = 1000.0;
//#line 28 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __default__.weight_final_x = 10.0;
//#line 28 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      controller.abstract_parameters.push_back(NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::ParamDescription<double>("weight_final_x", "double", 0, "Weight parameters for final state x", "", &NmpcLocalPlannerReconfigureConfig::weight_final_x)));
//#line 28 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::ParamDescription<double>("weight_final_x", "double", 0, "Weight parameters for final state x", "", &NmpcLocalPlannerReconfigureConfig::weight_final_x)));
//#line 29 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __min__.weight_final_y = 0.0;
//#line 29 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __max__.weight_final_y = 1000.0;
//#line 29 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __default__.weight_final_y = 1.0;
//#line 29 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      controller.abstract_parameters.push_back(NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::ParamDescription<double>("weight_final_y", "double", 0, "Weight parameters for final state y", "", &NmpcLocalPlannerReconfigureConfig::weight_final_y)));
//#line 29 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::ParamDescription<double>("weight_final_y", "double", 0, "Weight parameters for final state y", "", &NmpcLocalPlannerReconfigureConfig::weight_final_y)));
//#line 30 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __min__.weight_final_theta = 0.0;
//#line 30 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __max__.weight_final_theta = 1000.0;
//#line 30 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __default__.weight_final_theta = 10.0;
//#line 30 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      controller.abstract_parameters.push_back(NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::ParamDescription<double>("weight_final_theta", "double", 0, "Weight parameters for final state theta", "", &NmpcLocalPlannerReconfigureConfig::weight_final_theta)));
//#line 30 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::ParamDescription<double>("weight_final_theta", "double", 0, "Weight parameters for final state theta", "", &NmpcLocalPlannerReconfigureConfig::weight_final_theta)));
//#line 31 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __min__.weight_final_speed = 0.0;
//#line 31 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __max__.weight_final_speed = 1000.0;
//#line 31 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __default__.weight_final_speed = 10.0;
//#line 31 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      controller.abstract_parameters.push_back(NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::ParamDescription<double>("weight_final_speed", "double", 0, "Weight parameters for final state speed", "", &NmpcLocalPlannerReconfigureConfig::weight_final_speed)));
//#line 31 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::ParamDescription<double>("weight_final_speed", "double", 0, "Weight parameters for final state speed", "", &NmpcLocalPlannerReconfigureConfig::weight_final_speed)));
//#line 32 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __min__.weight_acc = 0.0;
//#line 32 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __max__.weight_acc = 1000.0;
//#line 32 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __default__.weight_acc = 10.0;
//#line 32 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      controller.abstract_parameters.push_back(NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::ParamDescription<double>("weight_acc", "double", 0, "Weight parameters for control acceleration", "", &NmpcLocalPlannerReconfigureConfig::weight_acc)));
//#line 32 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::ParamDescription<double>("weight_acc", "double", 0, "Weight parameters for control acceleration", "", &NmpcLocalPlannerReconfigureConfig::weight_acc)));
//#line 33 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __min__.weight_steer = 0.0;
//#line 33 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __max__.weight_steer = 1000.0;
//#line 33 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __default__.weight_steer = 10.0;
//#line 33 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      controller.abstract_parameters.push_back(NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::ParamDescription<double>("weight_steer", "double", 0, "Weight parameters for control steer", "", &NmpcLocalPlannerReconfigureConfig::weight_steer)));
//#line 33 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::ParamDescription<double>("weight_steer", "double", 0, "Weight parameters for control steer", "", &NmpcLocalPlannerReconfigureConfig::weight_steer)));
//#line 34 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __min__.weight_steer_acc = 0.0;
//#line 34 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __max__.weight_steer_acc = 1000.0;
//#line 34 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __default__.weight_steer_acc = 10.0;
//#line 34 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      controller.abstract_parameters.push_back(NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::ParamDescription<double>("weight_steer_acc", "double", 0, "Weight parameters for control steer rate", "", &NmpcLocalPlannerReconfigureConfig::weight_steer_acc)));
//#line 34 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::ParamDescription<double>("weight_steer_acc", "double", 0, "Weight parameters for control steer rate", "", &NmpcLocalPlannerReconfigureConfig::weight_steer_acc)));
//#line 35 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __min__.weight_left_side = 0.0;
//#line 35 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __max__.weight_left_side = 1000.0;
//#line 35 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __default__.weight_left_side = 5.0;
//#line 35 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      controller.abstract_parameters.push_back(NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::ParamDescription<double>("weight_left_side", "double", 0, "Weight parameters for left sidewalk", "", &NmpcLocalPlannerReconfigureConfig::weight_left_side)));
//#line 35 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::ParamDescription<double>("weight_left_side", "double", 0, "Weight parameters for left sidewalk", "", &NmpcLocalPlannerReconfigureConfig::weight_left_side)));
//#line 36 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __min__.weight_right_side = 0.0;
//#line 36 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __max__.weight_right_side = 1000.0;
//#line 36 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __default__.weight_right_side = 5.0;
//#line 36 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      controller.abstract_parameters.push_back(NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::ParamDescription<double>("weight_right_side", "double", 0, "Weight parameters for rightsidewalk", "", &NmpcLocalPlannerReconfigureConfig::weight_right_side)));
//#line 36 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::ParamDescription<double>("weight_right_side", "double", 0, "Weight parameters for rightsidewalk", "", &NmpcLocalPlannerReconfigureConfig::weight_right_side)));
//#line 37 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __min__.weight_obs = 0.0;
//#line 37 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __max__.weight_obs = 1000.0;
//#line 37 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __default__.weight_obs = 5.0;
//#line 37 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      controller.abstract_parameters.push_back(NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::ParamDescription<double>("weight_obs", "double", 0, "Weight parameters for obstacles", "", &NmpcLocalPlannerReconfigureConfig::weight_obs)));
//#line 37 "/home/hao/ros_ws/src/nmpc_local_planner/cfg/NmpcLocalPlannerReconfigure.cfg"
      __param_descriptions__.push_back(NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::ParamDescription<double>("weight_obs", "double", 0, "Weight parameters for obstacles", "", &NmpcLocalPlannerReconfigureConfig::weight_obs)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      controller.convertParams();
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(NmpcLocalPlannerReconfigureConfig::AbstractGroupDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::GroupDescription<NmpcLocalPlannerReconfigureConfig::DEFAULT::CONTROLLER, NmpcLocalPlannerReconfigureConfig::DEFAULT>(controller)));
//#line 124 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(NmpcLocalPlannerReconfigureConfig::AbstractGroupDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::GroupDescription<NmpcLocalPlannerReconfigureConfig::DEFAULT::CONTROLLER, NmpcLocalPlannerReconfigureConfig::DEFAULT>(controller)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(NmpcLocalPlannerReconfigureConfig::AbstractGroupDescriptionConstPtr(new NmpcLocalPlannerReconfigureConfig::GroupDescription<NmpcLocalPlannerReconfigureConfig::DEFAULT, NmpcLocalPlannerReconfigureConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<NmpcLocalPlannerReconfigureConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<NmpcLocalPlannerReconfigureConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    NmpcLocalPlannerReconfigureConfig __max__;
    NmpcLocalPlannerReconfigureConfig __min__;
    NmpcLocalPlannerReconfigureConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const NmpcLocalPlannerReconfigureConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static NmpcLocalPlannerReconfigureConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &NmpcLocalPlannerReconfigureConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const NmpcLocalPlannerReconfigureConfig &NmpcLocalPlannerReconfigureConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const NmpcLocalPlannerReconfigureConfig &NmpcLocalPlannerReconfigureConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const NmpcLocalPlannerReconfigureConfig &NmpcLocalPlannerReconfigureConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<NmpcLocalPlannerReconfigureConfig::AbstractParamDescriptionConstPtr> &NmpcLocalPlannerReconfigureConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<NmpcLocalPlannerReconfigureConfig::AbstractGroupDescriptionConstPtr> &NmpcLocalPlannerReconfigureConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const NmpcLocalPlannerReconfigureConfigStatics *NmpcLocalPlannerReconfigureConfig::__get_statics__()
  {
    const static NmpcLocalPlannerReconfigureConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = NmpcLocalPlannerReconfigureConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __NMPCLOCALPLANNERRECONFIGURERECONFIGURATOR_H__
